AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunctionOverHttps:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        HttpPost:
          Type: AWS::Serverless::Api
          Properties:
		     Name: Basic AWS Api Gateway
			 StageName: Staging
			 Auth:
			    Authorizers:
				   BasicAuthorizer:
				     FunctionPayloadType: TOKEN
					 FunctionArn: !ImportValue BasicAuthorizerFunction-Arn
					 Identity:
					   Header: Authorization
					   ValidationExpression: ^[Bb]earer [-0-9a-zA-z\.]*$
					    ReauthorizeEvery: 0
				DefaultAuthorizer: BasicAuthorizer
			 Cors: "'*'"
			 DefinitionBody:
			    'Fn::Transform':
				  Name: 'AWS::Include'
				  Parameters:
				     Location: s3://my-deploy-bucket/swagger.yaml
